### ISSUE TITLE
Builld failure in ubuntu

### ISSUE THREAD

**Issue by gameofwar12** [kpcyrd/sn0int#131]
while running "cargo install -f --path" command in ubuntu 19 the following error has failed the build process 

------------------------------------------------------------------------------------------------------------------------
error: enum variants on type aliases are experimental
   --> /home/mr-war/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.1/src/lib.rs:260:9
    |
260 |         Self::Client(s)
    |         ^^^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> /home/mr-war/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-rustls-0.10.1/src/lib.rs:266:9
    |
266 |         Self::Server(s)
    |         ^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `tokio-rustls`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sn0int v0.13.0 (/home/mr-war/BatCave/sn0int-master)`, intermediate artifacts can be found at `/home/mr-war/BatCave/sn0int-master/target`

Caused by:
  build failed

**Comment by kpcyrd** [comment]
Hello!

Your compiler is probably too old, we recommend installing it from https://rustup.rs/ or using the docker image.

**Comment by gameofwar12** [comment]
@kpcyrd Thanks for info
