### ISSUE TITLE
Failed building of sn0int

### ISSUE THREAD

**Issue by DanieleCalzetti** [kpcyrd/sn0int#165]
## Type of error

I am trying to reinstall Sn0int, when i type 
`cargo install -f --path .`

It returns the error displayed in the picture.   

![sn0int_error](https://user-images.githubusercontent.com/42589860/77407638-dbe09900-6d8c-11ea-91b3-a48b54d0702c.png)

I installed rust+cargo via rustup as indicated in the guide and I checked if cargo was already installed via packet manager but it doesn't seems installed. 
I tried to type:

`apt-get remove cargo `

It returned 

`Package 'cargo' is not installed, so not removed
`
---

## Versions

- **rustc --version:  rustc 1.42.0
- **cargo --version: cargo 1.42.0
- **sn0int --version: trying to install sn0int v0.18.2
- **uname -a: Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

**Comment by kpcyrd** [comment]
hey,
```
apt install pkg-config libsodium-dev
```
should fix this

**Comment by DanieleCalzetti** [comment]
Ok, that really worked well, thank you very much. 
Now I have another issue.
I attach the screenshot. 

A question to understand, it is related to some missing libraries? 

What can I study to understand it a little bit better? I am noob but I'd like to learn more and to understand more such issues. 

![image](https://user-images.githubusercontent.com/42589860/77516988-b36ea280-6e51-11ea-95c9-95369e9ca02c.png)

**Comment by kpcyrd** [comment]
You're also missing libseccomp:
```
apt install libseccomp-dev
```

**Comment by DanieleCalzetti** [comment]
Well thanks! It works! 
I close the issue.
