### ISSUE TITLE
Failed to download GeoIP database

### ISSUE THREAD

**Issue by jffin** [kpcyrd/sn0int#191]
**rustc --version:**```rustc 1.48.0 (7eac88abb 2020-11-16)```

**cargo --version:**```cargo 1.48.0 (65cbdd2dc 2020-10-14)```

**sn0int --version:**```sn0int 0.14.0```

**uname -a:**```Linux 33fdc085781a 4.19.0-12-cloud-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 Linux```

operation system is ```alpine```
installed with ```apk add sn0int```

**Error:**

```
        osint | recon | security
      irc.hackint.org:6697/#sn0int

[+] Connecting to database
[+] Downloading public suffix list
Error: Failed to download GeoIP database
Because: http request failed
Because: error trying to connect: dns server returned error: NXDomain
```

Seems like it does not depend on a host machine. Tried on different.

**Comment by kpcyrd** [comment]
Thanks for the detailed bug report! This file used to be downloaded from maxmind but was [taken down](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) end of 2019.

Any chance you can upgrade from alpine 3.11 to 3.12? If you can't, you can manually download the files and copy them to `~/.cache/sn0int/GeoLite2-City.mmdb` and `~/.cache/sn0int/GeoLite2-ASN.mmdb`.
