### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by Dalot** [kpcyrd/sn0int#192]
Build fails when running `cargo build`

```
error: failed to run custom build command for `libsodium-sys v0.2.6`

Caused by:
  process didn't exit successfully: `...\sn0int\target\release\build\libsodium-sys-21cd6ef957ef1835\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SODIUM_LIB_DIR
  cargo:rerun-if-env-changed=SODIUM_SHARED
  cargo:rerun-if-env-changed=SODIUM_USE_PKG_CONFIG

  --- stderr
  thread 'main' panicked at 'SODIUM_USE_PKG_CONFIG is not supported on msvc', ...\.cargo\registry\src\github.com-1ecc6299db9ec823\libsodium-sys-0.2.6\build.rs:90:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
---

## Versions

- **rustc --version:**
```rustc 1.48.0```
- **cargo --version:**
```cargo 1.48.0```
- **sn0int --version:**
```0.19.1```
- **uname -a:**
```MINGW64_NT-10.0-19042 - 3.1.7-340.x86_64 2020-10-23 Msys```

## Environment

- **Operating System/Distro:**
``` Windows 10```
- **Installed from (source/apt/pacman/brew/docker):**
```source```

**Comment by kpcyrd** [comment]
Windows isn't properly tested, but you might be able to build it by opening `sn0int-std/Cargo.toml` and changing:
```
sodiumoxide = { version="0.2.5", features=["use-pkg-config"] }
```
to
```
sodiumoxide = { version="0.2.5" }
```
Building in wsl is probably easier, but not officially supported either.

**Comment by Dalot** [comment]
It worked!
