### ISSUE TITLE
option at line 17 is not recognized

### ISSUE THREAD

**Issue by LogoiLab** [kpcyrd/sn0int#193]
I have an issue with sn0int always returning the following error for every module I run:
```
option at line 17 is not recognized
```
I tried cleaning out all sn0int configs and data and fully reinstalling and recompiling sn0int. After doing so and attempting to run `pkg quickstart` I got the following error:
```
[-] Failed to load dns configuration
Because: option at line 17 is not recognized
```
I am using DNSCrypt with systemd-resolved. At first I thought it was a VPN issue after extensive testing on multiple workspaces with different VPN and Non-VPN configurations I still get the same error.

I have searched sn0int github issues and found no one with my particular issue.

It would be helpful to have more verbose errors such as which file has the bad line.

---

## Versions

- **rustc --version:*rustc 1.50.0-nightly (1c389ffef 2020-11-24)*
- **cargo --version:*cargo 1.50.0-nightly (bfca1cd22 2020-11-24)*
- **sn0int --version:*sn0int 0.19.1*
- **uname -a:*Linux arch 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux*

## Environment

- **Operating System/Distro:*Linux, ArchLinux*
- **Installed from (source/apt/pacman/brew/docker):*both cargo and pacman*

**Comment by kpcyrd** [comment]
Thanks for the detailed report! Sorry that you tried multiple ways and they all didn't work, this issue has been fixed on master a while ago but we never got around to release it. We tagged a new 0.20.0 that contains the fix., please reach out if you're still having issues with that version. Thanks!
