### ISSUE TITLE
kpcyrd/pgp-keyserver Script returned error: "http error: 502"

### ISSUE THREAD

**Issue by acheong08** [kpcyrd/sn0int#198]
pgp module returns error when run with any domain

```
[sn0int][default][kpcyrd/pgp-keyserver] > workspace demo
[+] Connecting to database
[sn0int][demo][kpcyrd/pgp-keyserver] > add domain 
[?] Domain: medium.com
[sn0int][demo][kpcyrd/pgp-keyserver] > run
[-] "medium.com"                                      : Script returned error: "http error: 502"
[+] Finished kpcyrd/pgp-keyserver (1 errors)
[sn0int][demo][kpcyrd/pgp-keyserver] > 
```

---

## Versions

- **rustc --version: 1.51.0**
- **cargo --version: 1.51.0**
- **sn0int --version: 0.20.1**
- **uname -a: Darwin localhost.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64**

## Environment

- **Operating System/Distro: OSX**
- **Installed from (source/apt/pacman/brew/docker): brew**

**Comment by kpcyrd** [comment]
hey!

The server replied with an error so there isn't much we can do besides maybe better error messages. It's either the keyserver being overloaded or the query has too many results.
