### ISSUE TITLE
Error: No nameserver configured

### ISSUE THREAD

**Issue by anoduck** [kpcyrd/sn0int#204]
### No Nameserver

Upon attempting to install modules with `pkg quickstart`, I am given the following error.

```bash
[-] error trying to connect: No nameserver configured
```  
Dnscrypt-proxy is my DNS resolution provider which runs on localhost and listens on port 53, so nothing out of the ordinary. 

----

### Generating zsh completions

It would be nice to generate the zsh completions for sn0int, and the command `sn0int completions zsh` does generate them successfully and then dumps output on the command line. I just don't know where I am suppose to place them or how to properly set them up in `.zshrc`.

---

## Versions

- **rustc --version: 1.52.1** 
- **cargo --version: 1.52.0**
- **sn0int --version: 0.21.1**
- **uname -a: OpenBSD My.Host 6.9 GENERIC.MP#72 amd64**

## Environment

- **Operating System/Distro: OpenBSD CURRENT**
- **Installed from (source/apt/pacman/brew/docker): Both OpenBSD pkg, then source**

**Comment by kpcyrd** [comment]
Can you paste your `/etc/resolv.conf`?

**Comment by anoduck** [comment]
Hey @kpcyrd,
My first issue is now resolved, I had forgotten that I modified dhclient.conf to `ignore domain-name-servers;` while setting up dnscrypt-proxy. Once I commented out the line and replaced it with `supersede domain-name-servers 127.0.0.1;` sn0int worked like a charm. 

And the completions are setup and working good. 

Thanks!

**Comment by kpcyrd** [comment]
Awesome, glad to hear that! :)
