### ISSUE TITLE
Export Workspaces

### ISSUE THREAD

**Issue by gso-trifork-security** [kpcyrd/sn0int#230]
Hello, I can't really find a method to export a workspace. Is it even possible?

**Comment by kpcyrd** [comment]
There are two commands to export a workspace:

```sh
sn0int -w CHANGEME export --format json > export.json
```

By default binary blobs (like images) are not included, if you want to take a full export use:

```sh
sn0int -w CHANGEME export --format json-blobs > export.json
```
