### ISSUE TITLE
EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by AbdallaIbrahemMahmoud** [kpcyrd/sn0int#235]
Hello!

I just installed the sn0int package in Ubuntu but when i use a pkg to search about subdomain , I get an error ' EOF while parsing a value at line 1 column 0'

Anyone can lead me to how to solve it

Thanks in-advance

**Comment by roseninc** [comment]
Getting the exact same issue here - Using the tool via a Tracelabs OSINT vm

**Comment by SherkeyXD** [comment]
Same problem on Kali(inside vmware), using ctlogs

**Comment by kpcyrd** [comment]
Thanks for reporting this, this should be fixed with 0.24.3 that I'm releasing right now.

I've also made sure sn0int reports `Sandbox child has crashed` as the error instead of the somewhat obscure error that was due to trying to parse an empty string as json.
