### ISSUE TITLE
Dependency geo-types fails to build with Rust 1.67.0

### ISSUE THREAD

**Issue by ZhongRuoyu** [kpcyrd/sn0int#238]
Hi! Homebrew contributor here. While testing `rust` 1.67.0 in https://github.com/Homebrew/homebrew-core/pull/121561, we encountered failure while building `sn0int` 0.24.3. The failure seems related to its dependency `geo-types`:

```plaintext
     Compiling geo-types v0.7.7
  error: expected `,`, found `.`
     --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/geo-types-0.7.7/src/geometry/geometry_collection.rs:111:25
      |
  111 | #[deprecated(since = 0.7.5, note = "Use `GeometryCollection::from(vec![geom])` instead.")]
      |                         ^ expected `,`
  
  error: could not compile `geo-types` due to previous error
```

The error was extracted from [a run](https://github.com/Homebrew/homebrew-core/actions/runs/4018797239/jobs/6904946339#step:10:6814) on ARM-based macOS running Monterey, but it shouldn't be platform-specific. It seems related to https://github.com/georust/geo/pull/932, and should be fixed by bumping the `geo` dependency to a newer version. From what I see from https://github.com/georust/geo/commit/dbe5b4f1264fcf855e9c56096306e1bae65804aa, the fix was released in `geo` 0.23.1, which ships `geo-types` 0.7.8.

Thanks!

**Comment by ZhongRuoyu** [comment]
Thanks @kpcyrd for making the new release!

**Comment by kpcyrd** [comment]
You're welcome, let me know if there's something else I need to do to fix the homebrew package!
