### ISSUE TITLE
[-] error trying to connect: invalid certificate: CertExpired

### ISSUE THREAD

**Issue by andre-santos1** [kpcyrd/sn0int#267]
please describe your issue here

When I run pkg quickstart I get:

[-] error trying to connect: invalid certificate: CertExpired

## Versions

- **rustc --version: bash: rustc: command not found
- **cargo --version: bash: cargo: command not found

- **sn0int --version: 0.25.0
- **uname -a: Linux debian 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

## Environment

- **Operating System/Distro: Linux debian
- **Installed from (source/apt/pacman/brew/docker):
-

cd ~/Programs
sudo apt install curl sq -y
curl -sSf https://apt.vulns.sexy/kpcyrd.pgp | sq dearmor | sudo tee /etc/apt/trusted.gpg.d/apt-vulns-sexy.gpg
echo deb http://apt.vulns.sexy stable main | sudo tee /etc/apt/sources.list.d/apt-vulns-sexy.list
sudo apt update && sudo apt install sn0int

**Comment by kpcyrd** [comment]
Thanks, this is related to https://github.com/kpcyrd/acme-redirect/issues/40

**Comment by andre-santos1** [comment]
Thanks I'll check that!

**Comment by kpcyrd** [comment]
Should be fine again
