### ISSUE TITLE
Error message when using cargo install

### ISSUE THREAD

**Issue by PieElecAm** [kpcyrd/sn0int#66]
Compiling libc v0.2.48
   Compiling utf-8 v0.7.5
   Compiling fnv v1.0.6
error: invalid format string: expected `'}'`, found `'?'`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/utf-8-0.7.5/src/read.rs:40:27
   |
40 |                 write!(f, "invalid byte sequence: {:02x?}", bytes)
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: invalid format string: expected `'}'`, found `'?'`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/utf-8-0.7.5/src/lib.rs:42:17
   |
42 | /                 "found invalid byte sequence {invalid_sequence:02x?} after \
43 | |                  {valid_byte_count} valid bytes, followed by {unprocessed_byte_count} more \
44 | |                  unprocessed bytes",
   | |___________________________________^

error: invalid format string: expected `'}'`, found `'?'`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/utf-8-0.7.5/src/lib.rs:54:17
   |
54 | /                 "found incomplete byte sequence {incomplete_suffix:02x?} after \
55 | |                  {valid_byte_count} bytes",
   | |__________________________________________^

error: aborting due to 3 previous errors

error: Could not compile `utf-8`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sn0int v0.8.1 (file:///home/Desktop/Downloaded%20Tools/sn0int)`, intermediate artifacts can be found at `/home/Desktop/Downloaded Tools/sn0int/target`

Caused by:
  build failed

**Comment by kpcyrd** [comment]
@PieElecAm thanks for your report, I'm going to look into this! It seems like your rust version is outdated, can you give me the output of this command?

```
rustc --version
```

Thanks!

**Comment by kpcyrd** [comment]
This is most likely related to the rust version, please reopen if you have additional information. Thanks!
