### ISSUE TITLE
error: cargo install: diesel: unable to get packages from source

### ISSUE THREAD

**Issue by roycewilliams** [kpcyrd/sn0int#68]
Could this be a transient connectivity issue?

```
 Downloading diesel v1.4.1                                                                                                                
error: failed to compile `sn0int v0.9.0 (/[redacted]/sn0int)`, intermediate artifacts can be found at `[redacted]/sn0int/target`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.1/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

consider adding `cargo-features = ["rename-dependency"]` to the manifest

```

**Comment by Athrekas** [comment]
Same issue here.

**Comment by kpcyrd** [comment]
Thanks for your report! The problem seems to be `failed to parse manifest at /home/[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.1/Cargo.toml` which shouldn't happen and might indicate an outdated cargo version.

How did you install rust (from your distro or rustup) and which version of rust and cargo are you using? You can get these with:
```
rustc --version
cargo --version
```

Thanks!

**Comment by gibbypip** [comment]
removing the apt version of rustc and using rustup fixed the issue for me.

**Comment by kpcyrd** [comment]
@gibbypip Awesome! Out of interest, which distro are you on if you don't mind me asking? :)

**Comment by roycewilliams** [comment]
FWIW, my setup is:
```
$ rustc --version
rustc 1.30.0
$ cargo --version
cargo 1.30.0
$ grep DESC /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

**Comment by gibbypip** [comment]
@kpcyrd:

Vanilla install of Ubuntu Server 18.04 LTS after a quick apt update/upgrade

**Comment by scottellis** [comment]
Same with workstation 18.10

I added 

    cargo-features = ["rename-dependency"]

to 

    ~/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.1/Cargo.toml

and then got the following error

    ~/sn0int$ cargo install -f --path .
      Installing sn0int v0.9.0 (/home/scott/sn0int)
     Downloading caps v0.3.0
     Downloading rand v0.6.5
     Downloading syscallz v0.8.0
     Downloading sloppy-rfc4880 v0.1.2
     ...
       Compiling proc-macro-hack-impl v0.4.1
       Compiling rustc-demangle v0.1.13
       Compiling safemem v0.3.0
       Compiling dtoa v0.4.3
       Compiling num-bigint v0.2.2
       Compiling procedural-masquerade v0.1.6
       Compiling string v0.1.3
       Compiling precomputed-hash v0.1.1
       Compiling data-encoding v2.1.2
    error: Edition 2018 is unstable and only available for nightly builds of rustc.

    error: Could not compile `data-encoding`.
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `sn0int v0.9.0 (/home/scott/sn0int)`, intermediate artifacts can be found at 
    `/home/scott/sn0int/target`

    Caused by:
      build failed

I don't know whether or not that is useful.

**Comment by kpcyrd** [comment]
The compiler in ubuntu is too old, sorry. Right now you would need to install a more recent rust version with rustup or use the docker image.

I've documented this in the install instructions: https://sn0int.readthedocs.io/en/latest/install.html#ubuntu-debian-stable

**Comment by roycewilliams** [comment]
Ah, ok - thanks!

**Comment by roycewilliams** [comment]
Is this true even for Ubuntu 18.04?

**Comment by scottellis** [comment]
I get the same error with 18.10 so I would think yes.
