### ISSUE TITLE
Error: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by csak-9604** [kpcyrd/sn0int#70]
Hello, 
Following your tutorial, I get the following Error:
`[sn0int][example][kpcyrd/ctlogs] > select domains `
`[sn0int][example][kpcyrd/ctlogs] > add domain`
`[?] Domain: example.com`
`[sn0int][example][kpcyrd/ctlogs] > run`
`[-] Failed "example.com": EOF while parsing a value at line 1 column 0`
`[+] Finished kpcyrd/ctlogs (1 errors)`

**Comment by kpcyrd** [comment]
hey, thanks for your report!

This is probably a seccomp failure, which means the child used a syscall that hasn't been whitelisted and got killed.

If you're on systemd, can you check if a coredump has been written by running `coredumpctl` and checking if there's something related to sn0int?

Also, which distro and architecture are you using? (uname -m)

**Comment by csak-9604** [comment]
Hello, 
Thanks for the reply. 
`root@kali:~# uname -a`
`Linux kali 4.19.0-kali1-686-pae #1 SMP Debian 4.19.13-1kali1 (2019-01-03) i686 `GNU/Linux`

I could not find any sn0int related infos in the `systemd --dump-core`, but I am not sure if i am using it right.

**Comment by kpcyrd** [comment]
It's very likely i686 uses syscalls I haven't whitelisted just. I'm going to try this myself and make sure the sandbox works correctly on that architecture as well. This is going to be included in the next patch release.

Thanks for you help!

**Comment by csak-9604** [comment]
great! 
thank you

**Comment by jasonsperry** [comment]
I receive this as well running sn0wint on Kali in the Windows Linux Subsystem.  Do you think it would be caused by limitations in WLS or would it be whitelisting syscalls as for the i686 architecture?

`uname -a`
`Linux <MACHINENAME> 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 GNU/Linux`

**Comment by csak-9604** [comment]
hello,
works now. 
thank you

**Comment by kpcyrd** [comment]
@csak-9604 awesome!

@jasonsperry please try again with the current maser. In case that still fails please open a new issue that is WSL specific, but I'm not sure I'm officially going to support that :/ There's a section in the documentation about sandbox troubleshooting if you want to look into it: https://sn0int.readthedocs.io/en/latest/sandbox.html#diagnosing-a-sandbox-failure
